using MsftGps.MarketplaceAnalytics.Schema;

namespace MsftGps.AnalyticsTest
{
    public static class MarketplaceQueries
    {
        public static readonly string IsvCustomerSelectAll = @"
            SELECT 
                MarketplaceSubscriptionId,
                DateAcquired,
                DateLost,
                IsActive,
                ProviderName,
                ProviderEmail,
                FirstName,
                LastName,
                Email,
                CustomerCompanyName,
                CustomerCity,
                CustomerPostalCode,
                CustomerCommunicationCulture,
                CustomerCountryRegion,
                AzureLicenseType,
                PromotionalCustomers,
                CustomerState,
                CommerceRootCustomer,
                CustomerId,
                BillingAccountId,
                CustomerType,
                OfferName,
                PlanId,
                SKU 
            FROM 
                ISVCustomer";
        
        public static readonly string IsvOrderSelectAll = @"
            SELECT 
                MarketplaceSubscriptionId,
                MonthStartDate,
                OfferType,
                AzureLicenseType,
                MarketplaceLicenseType,
                SKU,
                CustomerCountry,
                IsPreviewSKU,
                AssetId,
                Quantity,
                CloudInstanceName,
                IsNewCustomer,
                OrderStatus,
                OrderCancelDate,
                CustomerCompanyName,
                OrderPurchaseDate,
                OfferName,
                IsPrivateOffer,
                TermStartDate,
                TermEndDate,
                PurchaseRecordId,
                PurchaseRecordLineItemId,
                BilledRevenue,
                Currency,
                HasTrial,
                IsTrial,
                TrialEndDate,
                OrderAction,
                QuantityChanged,
                EventTimestamp,
                CustomerId,
                BillingAccountId,
                PlanId,
                BillingTerm,
                BillingPlan,
                ReferenceId,
                AutoRenew,
                OrderVersion 
            FROM 
                ISVOrder";
        
        public static readonly string IsvUsageSelectAll = @"
            SELECT 
                MarketplaceSubscriptionId,
                MonthStartDate,
                OfferType,
                AzureLicenseType,
                MarketplaceLicenseType,
                SKU,
                CustomerCountry,
                IsPreviewSKU,
                SKUBillingType,
                VMSize,
                CloudInstanceName,
                OfferName,
                IsPrivateOffer,
                DeploymentMethod,
                CustomerName,
                CustomerCompanyName,
                UsageDate,
                IsNewCustomer,
                CoreSize,
                TrialEndDate,
                CustomerCurrencyCC,
                PriceCC,
                PayoutCurrencyPC,
                EstimatedPricePC,
                UsageReference,
                UsageUnit,
                CustomerId,
                BillingAccountId,
                MeterDimension,
                MeterId,
                PartnerCenterDetectedAnomaly,
                PublisherMarkedAnomaly,
                NewReportedUsage,
                ActionTakenAt,
                ActionTakenBy,
                PlanId,
                ReferenceId,
                NormalizedUsage,
                MeteredUsage,
                RawUsage,
                EstimatedExtendedChargeCC,
                EstimatedExtendedChargePC,
                EstimatedFinancialImpactUSD 
            FROM 
                ISVUsage";

        public static readonly string IsvMarketplaceInsightsSelectAll = @"
            SELECT 
                Date,
                OfferName,
                ReferralDomain,
                CountryName,
                PageVisits,
                GetItNow,
                ContactMe,
                TestDrive,
                FreeTrial,
                ConsentGiven,
                Site,
                Campaign 
            FROM 
                ISVMarketplaceInsights";

        public static string IsvRevenueSelectAll = @"
            SELECT 
                AssetId,
                SalesChannel,
                BillingAccountId,
                CustomerCity,
                CustomerCompanyName,
                CustomerCountry,
                CustomerEmail,
                CustomerId,
                CustomerName,
                CustomerState,
                EarningAmountCC,
                EarningAmountPC,
                EarningAmountUSD,
                EarningCurrencyCode,
                EarningExchangeRatePC,
                EstimatedPayoutMonth,
                Revenue,
                EstimatedRevenuePC,
                EstimatedRevenueUSD,
                ExchangeRateDate,
                ExchangeRatePC,
                ExchangeRateUSD,
                PayoutStatus,
                IncentiveRate,
                TrialDeployment,
                LineItemId,
                MonthStartDate,
                OfferName,
                OfferType,
                PaymentInstrumentType,
                PaymentSentDate,
                PurchaseRecordId,
                Quantity,
                SKU,
                TermEndDate,
                TermStartDate,
                TransactionAmountCC,
                TransactionAmountPC,
                TransactionAmountUSD,
                BillingModel,
                Units,
                PlanId,
                IsPrivateOffer 
            FROM 
                ISVRevenue";

        public static readonly string IsvOfferRetentionSelectAll = @"
            SELECT 
                OfferCategory,
                OfferName,
                ProductId,
                Sku,
                SkuBillingType,
                CustomerId,
                CustomerName,
                CustomerCompanyName,
                CustomerCountryName,
                CustomerCountryCode,
                CustomerCurrencyCode,
                FirstUsageDate,
                AzureLicenseType,
                OfferType,
                Offset  
            FROM 
                ISVOfferRetention";

        public static readonly string IsvQualityOfServiceSelectAll = @"
            SELECT 
                OfferId,
                Sku,
                DeploymentStatus,
                DeploymentCorrelationId,
                SubscriptionId,
                CustomerTenantId,
                CustomerName,
                TemplateType,
                StartTime,
                EndTime,
                DeploymentDurationInMilliSeconds,
                DeploymentRegion,
                ResourceProvider,
                ResourceUri,
                ResourceGroup,
                ResourceType,
                ResourceName,
                ErrorCode,
                ErrorName,
                ErrorMessage,
                DeepErrorCode,
                DeepErrorMessage 
            FROM 
                ISVQualityOfService";
    }
}